
- name: "Run installation d'ISS"
  hosts: "windows"
  gather_facts: "false"
  tasks :
   - name: ensure 7-Zip is installed via Chocolatey
     win_chocolatey:
          name: 7zip
          state: present
   - name: installation de chrome
     win_chocolatey:
          name: googlechrome
          state: present
   - name: installation de adobe reader
     win_chocolatey:
          name: adobereader
          state: present
   - name : installation d ISS webdeploy pas encore configure  
     win_chocolatey:
          name: webdeploy
          state: present
   - name: Add ACME webapplication on IIS modifie pour test jenkins
     win_iis_webapplication:
        name: api
        site: acme
        state: present
        physical_path: C:\site
   - name: Copy a single file
     win_copy:
        src: /etc/ansible/deployiss2/welcome2.html
        dest: c:\site\    
   - name: Copy a single file
     win_copy:
        src: /etc/ansible/deployiss2/pendu.py
        dest: c:\site\ 
 
